### PR TITLE
Remove show_in_footer, Fix Specs

### PR DESCRIPTION
**Pull request by nishant-cyro**

### CODE REVIEW

**Comment by Mafi88** [comment]
@nishant-cyro Please describe why you removed show_in_footer.

**Comment by nishant-cyro** [comment]
@Mafi88 - According to the new designs of Spree, there is no footer in it.

**Comment by Mafi88** [comment]
@nishant-cyro Thanks.
:+1:

**Comment by damianlegawiec** [comment]
@nishant-cyro can you sync with master? Thanks :)

**Comment by nishant-cyro** [comment]
@damianlegawiec - done!

**Comment by nishant-cyro** [comment]
@damianlegawiec - Fixed, using html now.

**Pull request merged**
